# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
 - linux
 - osx

r:
 - oldrel

# - osx for devel have issues to install devtools
# - after success on the release version, run coverage checks
matrix:
 include:
 - r: devel
   os: linux
 - r: release
   after_success:
    - Rscript -e 'covr::codecov()'

# system requirements for rJava and topicmodels packages
# http://stackoverflow.com/questions/16438073/unable-to-install-rjava-in-r-3-0-in-ubuntu-13-04?rq=1
# http://stackoverflow.com/questions/25759007/error-installing-topicmodels-package-non-zero-exit-status-ubuntu
before_install:
  - sudo apt-get install libgsl0-dev openjdk-7-*

r_packages: devtools
